def sing():
    print("Old MacDonald had a farm, Ee-igh, Ee-igh, oh!")
def name(sound):
    print("with a "+sound+" ,"+sound+" here and a "+sound+", "+sound+" there")
def animal(peru):
    print("and on that farm he had a "+peru+", Ee-igh, Ee-igh, oh!")
def chan():
    sing()
    animal('cow')
    name('moo')
    sing()
    print()
    sing()
    animal('Tiger')
    name('roo')
    sing()
    print()
    sing()
    animal('cat')
    name('meow')
    sing()
    print("")
    sing()
    animal('dog')
    name('bow-bow')
    sing()
    print()
chan()